TriggerEvent('es:addCommand', 'help', function(source, args, user)
    TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = '/showjob for job info' })
	Citizen.Wait(2500)
	TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = '/showbank for bank money' })
	Citizen.Wait(2500)
	TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = '/showdirty for blac kmoney' })
	Citizen.Wait(2500)
	TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = '/showcash for hand cash' })
	Citizen.Wait(2500)
	TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = '/showinfo for watch all' })
	Citizen.Wait(2500)
	TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = 'Press H to handsUP' })
	Citizen.Wait(2500)
	TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = 'press F1 for phone' })
	Citizen.Wait(2500)
	TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = 'press F2 for inventory' })
	Citizen.Wait(2500)
	TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = 'press U for server ID' })
	Citizen.Wait(2500)
	TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = 'press B for SeatBelt' })
	Citizen.Wait(2500)
	TriggerClientEvent('mythic_notify:client:SendAlert', source, { type = 'inform', text = 'press F6 for Job Menus' })
	Citizen.Wait(2500)
end)